<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 8/8/17
 * Time: 3:48 PM
 */
namespace frontend\widgets\demopager;

use yii\web\AssetBundle;

class DemoPagerAsset extends AssetBundle
{
    public $js = [
        'js/demopager.js'
    ];

//    public $css = [
//        'css/demopager.css'
//    ];

    public $depends = [
        'yii\web\JqueryAsset'
    ];

    public function init()
    {
        $this->sourcePath =__DIR__ . "/assets";
        parent::init(); // TODO: Change the autogenerated stub

    }
}