<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 8/8/17
 * Time: 3:48 PM
 */
use yii\widgets\LinkPager;

class DemoPager extends LinkPager
{
    public $pager_layout = '{pageButtons} {pageSizeList} {goTopage}';
    private $pageSizeList = [5,10,20,30];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $currentPageSize = $this->pagination->getPageSize();

        if (!in_array($currentPageSize, $this->pageSizeList)){
            array_unshift($this->pageSizeList, $currentPageSize);
            $this->pageSizeList = array_unique($this->pageSizeList);

            sort($this->pageSizeList, SORT_NUMERIC);
        }
    }

    public function run()
    {
        return preg_replace_callback_array("/{(\\W+)}/", function ($matches){
            $sub_section_name = $matches[1];
            $sub_section_content = $this->renderSection($sub_section_name);

            return $sub_section_content == false ? $matches[1]: $sub_section_content;
        }, $this->pager_layout);
    }

    protected function renderSection($name){
        switch ($name){
            case 'pageButtons':
                return $this->renderPageButton();

            case 'pageSizeList':
                return $this->renderPageSizeList();

            case 'goToPage':
                return $this->rendergoToPage();

            default:
                return false;
        }
    }
}