<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 8/8/17
 * Time: 2:22 PM
 */

namespace frontend\votewidget;

use yii\web\AssetBundle;

class VoteWidgetAsset extends AssetBundle
{
    public $js = [
        'js/votewidget.js'
    ];

    public $css = [
        'css/votewidget.css',
        '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'
    ];

    public $depends = [
        'yii\web\JqueryAsset'
    ];

    public function init()
    {
        $this->sourcePath = __DIR__ . "/assets";
        parent::init(); // TODO: Change the autogenerated stub
    }
}