<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 8/8/17
 * Time: 1:48 PM
 */

namespace frontend\votewidget;

use yii\base\Widget;
use yii\helpers\Html;

class VoteWidget extends Widget
{
    public $model;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function run()
    {
       VoteWidgetAsset::register($this->getView());
       return $this->render('_vote', ['product' => $this->model]);
    }
}